name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
      - uses: dimensiondev/github-token-action@latest
        with:
          registry: true
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.16.0        
      - run: pnpm i
      - run: ./scripts/publish-to-github.sh
